PR-774 => develop
pib-rocks/pib-backend pull request #96
Opened 2024-11-28 15:29 UTC by VladislavStavila

# Jira Ticket:
Link to corresponding jira ticket:
https://pib-rocks.atlassian.net/jira/software/c/projects/PR/boards/3?selectedIssue=PR-724

# Checklist:
These tasks need to be completed before the pull request can be merged:
- [x] The code has been reviewed and approved at least once
- [x] All necessary tests have been successful
- [x] The product owner reviewed and accepted the story

# Testing:
### Test acceptance criteria:
- [x] No power notification on the screen
- [x] Pib(raspy 5 with pios) works without turning off

### Setup Tests:

A setup test was successfull on the following system(s):
- [x] Setup on a physical pib (raspy 5, pios)

2025-01-29 07:50 UTC, ElisabethTopilin requested changes

2025-02-17 10:48 UTC, VladislavStavila commented on setup/setup-pib.sh
> +sudo sh -c 'echo "force_turbo=1" >> /boot/firmware/config.txt'
done

2025-02-17 10:49 UTC, VladislavStavila commented on setup/setup-pib.sh
> +echo "kernel.panic = 0" | sudo tee -a
done

2025-02-17 10:49 UTC, VladislavStavila commented on setup/setup-pib.sh
> +echo "kernel.panic = 0" | sudo tee -a
is on the pib (pios 5)

2025-02-18 07:24 UTC, ElisabethTopilin approved these changes

2025-02-26 11:09 UTC, merged